version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: digitay_db
    ports:
      - "5434:5432"
    volumes:
      - pt_data:/var/lib/postgresql/data

volumes:
  pt_data:
